# Exploratory Analysis

This notebook contains the statistical analysis, distributions, groupby calculations, percentages, relationships, and findings for Q1–Q10.

In [20]:
print("Minimum Month:", clean_df['Month_Year'].min())
print("Maximum Month:", clean_df['Month_Year'].max())

Minimum Month: 2022-08-01 00:00:00
Maximum Month: 2026-07-01 00:00:00

In [21]:
# Display the first five rows to inspect the dataset structure.
clean_df.head()

,Month_Year,Area Type,Borough_SNT,Area Name,Area Code,Crime Type,Crime Subtype,Measure,Financial Year,Count,Refresh Date
0,2025-02-01,Safer Neighbourhood Teams,Lambeth Brixton Windrush,Brixton Windrush,E05014098,Knife Crime,Knife Crime with Injury,Offences,fy24-25,2,2026-08-18
1,2025-12-01,Safer Neighbourhood Teams,Croydon Selhurst,Selhurst,E05011479,Knife Crime,Knife Crime with Injury,Offences,fy25-26,1,2026-08-18
2,2024-01-01,Safer Neighbourhood Teams,Greenwich Abbey Wood,Abbey Wood,E05014072,Knife Crime,Knife Crime with Injury,Offences,fy23-24,2,2026-08-18
3,2024-12-01,Safer Neighbourhood Teams,Croydon West Thornton,West Thornton,E05011488,Knife Crime,Knife Crime with Injury,Offences,fy24-25,2,2026-08-18
4,2023-02-01,Safer Neighbourhood Teams,Waltham Forest Wood Street,Wood Street,E05013903,Knife Crime,Knife Crime with Injury,Offences,fy22-23,6,2026-08-18

In [22]:
print("Number of unique months:", clean_df['Month_Year'].nunique())

print("\nMonths:")
print(clean_df['Month_Year'].sort_values().unique())

Number of unique months: 48

Months:
<DatetimeArray>
['2022-08-01 00:00:00', '2022-09-01 00:00:00', '2022-10-01 00:00:00',
 '2022-11-01 00:00:00', '2022-12-01 00:00:00', '2023-01-01 00:00:00',
 '2023-02-01 00:00:00', '2023-03-01 00:00:00', '2023-04-01 00:00:00',
 '2023-05-01 00:00:00', '2023-06-01 00:00:00', '2023-07-01 00:00:00',
 '2023-08-01 00:00:00', '2023-09-01 00:00:00', '2023-10-01 00:00:00',
 '2023-11-01 00:00:00', '2023-12-01 00:00:00', '2024-01-01 00:00:00',
 '2024-02-01 00:00:00', '2024-03-01 00:00:00', '2024-04-01 00:00:00',
 '2024-05-01 00:00:00', '2024-06-01 00:00:00', '2024-07-01 00:00:00',
 '2024-08-01 00:00:00', '2024-09-01 00:00:00', '2024-10-01 00:00:00',
 '2024-11-01 00:00:00', '2024-12-01 00:00:00', '2025-01-01 00:00:00',
 '2025-02-01 00:00:00', '2025-03-01 00:00:00', '2025-04-01 00:00:00',
 '2025-05-01 00:00:00', '2025-06-01 00:00:00', '2025-07-01 00:00:00',
 '2025-08-01 00:00:00', '2025-09-01 00:00:00', '2025-10-01 00:00:00',
 '2025-11-01 00:00:00', '2025-12-01 00:00:00', '2026-01-01 00:00:00',
 '2026-02-01 00:00:00', '2026-03-01 00:00:00', '2026-04-01 00:00:00',
 '2026-05-01 00:00:00', '2026-06-01 00:00:00', '2026-07-01 00:00:00']
Length: 48, dtype: datetime64[us]

In [23]:
print("Unique Borough/SNT:", clean_df['Borough_SNT'].nunique())
print("Unique Area Names:", clean_df['Area Name'].nunique())
print("Unique Area Codes:", clean_df['Area Code'].nunique())

Unique Borough/SNT: 722
Unique Area Names: 719
Unique Area Codes: 715

In [24]:
print("Crime Types:")
print(clean_df['Crime Type'].value_counts())

print("\nCrime Subtypes:")
print(clean_df['Crime Subtype'].value_counts())

print("\nMeasures:")
print(clean_df['Measure'].value_counts())

print("\nFinancial Years:")
print(clean_df['Financial Year'].value_counts())

Crime Types:
Crime Type
Knife Crime    60100
Name: count, dtype: int64

Crime Subtypes:
Crime Subtype
Knife Crime                                   31102
Knife Crime with Injury                       15009
Knife Injury Victims (1-24)                    5694
Knife Injury Victims (non DA 1-24)             5300
Knife Crime with Injury (Personal Robbery)     2995
Name: count, dtype: int64

Measures:
Measure
Offences             48927
Positive Outcomes    11173
Name: count, dtype: int64

Financial Years:
Financial Year
fy25-26    15543
fy24-25    14812
fy23-24    14741
fy22-23     9803
fy26-27     5201
Name: count, dtype: int64

In [25]:
offences_df = clean_df[clean_df['Measure'] == 'Offences'].copy()

print("Offences dataset shape:", offences_df.shape)
print("Measures present:")
print(offences_df['Measure'].value_counts())

Offences dataset shape: (48927, 11)
Measures present:
Measure
Offences    48927
Name: count, dtype: int64

In [26]:
print("Total offence records:", len(offences_df))
print("Total knife-crime offences:", offences_df['Count'].sum())
print("Average offences per record:", offences_df['Count'].mean())
print("Maximum offences in a single record:", offences_df['Count'].max())

Total offence records: 48927
Total knife-crime offences: 171727
Average offences per record: 3.5098616305925154
Maximum offences in a single record: 110

In [27]:
print("\nOffence count statistics:")
print(offences_df['Count'].describe())

Offence count statistics:
count    48927.000000
mean         3.509862
std          7.626625
min          1.000000
25%          1.000000
50%          2.000000
75%          3.000000
max        110.000000
Name: Count, dtype: float64

In [28]:
monthly_offences = (
    offences_df
    .groupby('Month_Year')['Count']
    .sum()
    .reset_index()
)

print(monthly_offences)

   Month_Year  Count
0  2022-08-01   3342
1  2022-09-01   3250
2  2022-10-01   4090
3  2022-11-01   3388
4  2022-12-01   3002
5  2023-01-01   3422
6  2023-02-01   3494
7  2023-03-01   3442
8  2023-04-01   3342
9  2023-05-01   3530
10 2023-06-01   3662
11 2023-07-01   3758
12 2023-08-01   3830
13 2023-09-01   3756
14 2023-10-01   3334
15 2023-11-01   3976
16 2023-12-01   3896
17 2024-01-01   3586
18 2024-02-01   3479
19 2024-03-01   4070
20 2024-04-01   3680
21 2024-05-01   4510
22 2024-06-01   3960
23 2024-07-01   4076
24 2024-08-01   4088
25 2024-09-01   3842
26 2024-10-01   4090
27 2024-11-01   4010
28 2024-12-01   3686
29 2025-01-01   3406
30 2025-02-01   3146
31 2025-03-01   3386
32 2025-04-01   3666
33 2025-05-01   3476
34 2025-06-01   3672
35 2025-07-01   3824
36 2025-08-01   3188
37 2025-09-01   3162
38 2025-10-01   3334
39 2025-11-01   3092
40 2025-12-01   3078
41 2026-01-01   3038
42 2026-02-01   2856
43 2026-03-01   3582
44 2026-04-01   3368
45 2026-05-01   3864
46 2026-06-01   3580
47 2026-07-01   3418

In [29]:
print("Number of months:", monthly_offences['Month_Year'].nunique())

Number of months: 48

In [30]:
print("\nFirst 5 months:")
print(monthly_offences.head())

print("\nLast 5 months:")
print(monthly_offences.tail())

First 5 months:
  Month_Year  Count
0 2022-08-01   3342
1 2022-09-01   3250
2 2022-10-01   4090
3 2022-11-01   3388
4 2022-12-01   3002

Last 5 months:
   Month_Year  Count
43 2026-03-01   3582
44 2026-04-01   3368
45 2026-05-01   3864
46 2026-06-01   3580
47 2026-07-01   3418

In [31]:
highest_month = monthly_offences.loc[
    monthly_offences['Count'].idxmax()
]

lowest_month = monthly_offences.loc[
    monthly_offences['Count'].idxmin()
]

print("Highest offence month:")
print(highest_month)

print("\nLowest offence month:")
print(lowest_month)

Highest offence month:
Month_Year    2024-05-01 00:00:00
Count                        4510
Name: 21, dtype: object

Lowest offence month:
Month_Year    2026-02-01 00:00:00
Count                        2856
Name: 42, dtype: object

In [32]:
average_monthly = monthly_offences['Count'].mean()

print("Average monthly offences:", average_monthly)

Average monthly offences: 3577.6458333333335

In [33]:
first_month = monthly_offences.iloc[0]
last_month = monthly_offences.iloc[-1]

percentage_change = (
    (last_month['Count'] - first_month['Count'])
    / first_month['Count']
) * 100

print("First month:", first_month['Month_Year'])
print("First month offences:", first_month['Count'])

print("\nLast month:", last_month['Month_Year'])
print("Last month offences:", last_month['Count'])

print("\nPercentage change:", percentage_change, "%")

First month: 2022-08-01 00:00:00
First month offences: 3342

Last month: 2026-07-01 00:00:00
Last month offences: 3418

Percentage change: 2.2740873728306403 %

# Question 1 – How does the number of knife-crime offences change over time?

In [35]:
above_average = monthly_offences[
    monthly_offences['Count'] > average_monthly
]

print("Months above average:")
print(above_average)

Months above average:
   Month_Year  Count
2  2022-10-01   4090
10 2023-06-01   3662
11 2023-07-01   3758
12 2023-08-01   3830
13 2023-09-01   3756
15 2023-11-01   3976
16 2023-12-01   3896
17 2024-01-01   3586
19 2024-03-01   4070
20 2024-04-01   3680
21 2024-05-01   4510
22 2024-06-01   3960
23 2024-07-01   4076
24 2024-08-01   4088
25 2024-09-01   3842
26 2024-10-01   4090
27 2024-11-01   4010
28 2024-12-01   3686
32 2025-04-01   3666
34 2025-06-01   3672
35 2025-07-01   3824
43 2026-03-01   3582
45 2026-05-01   3864
46 2026-06-01   3580

In [36]:
print(
    "Number of months above average:",
    len(above_average)
)

Number of months above average: 24

# Question 2 – Which financial year recorded the highest number of knife-crime offences?

In [37]:

financial_year_offences = (
    offences_df
    .groupby('Financial Year')['Count']
    .sum()
    .reset_index()
)

print(financial_year_offences)

  Financial Year  Count
0        fy22-23  27430
1        fy23-24  44219
2        fy24-25  45880
3        fy25-26  39968
4        fy26-27  14230

In [38]:
financial_year_summary = (
    offences_df
    .groupby('Financial Year')
    .agg(
        Total_Offences=('Count', 'sum'),
        Records=('Count', 'count')
    )
    .reset_index()
)

print(financial_year_summary)

  Financial Year  Total_Offences  Records
0        fy22-23           27430     7896
1        fy23-24           44219    12264
2        fy24-25           45880    12595
3        fy25-26           39968    12059
4        fy26-27           14230     4113

In [39]:
highest_financial_year = financial_year_summary.loc[
    financial_year_summary['Total_Offences'].idxmax()
]

print("Financial year with highest offences:")
print(highest_financial_year)

Financial year with highest offences:
Financial Year    fy24-25
Total_Offences      45880
Records             12595
Name: 2, dtype: object

In [40]:
lowest_financial_year = financial_year_summary.loc[
    financial_year_summary['Total_Offences'].idxmin()
]

print("\nFinancial year with lowest offences:")
print(lowest_financial_year)

Financial year with lowest offences:
Financial Year    fy26-27
Total_Offences      14230
Records              4113
Name: 4, dtype: object

In [41]:
fy_order = [
    'fy22-23',
    'fy23-24',
    'fy24-25',
    'fy25-26',
    'fy26-27'
]

financial_year_summary['Financial Year'] = pd.Categorical(
    financial_year_summary['Financial Year'],
    categories=fy_order,
    ordered=True
)

financial_year_summary = (
    financial_year_summary
    .sort_values('Financial Year')
    .reset_index(drop=True)
)

print(financial_year_summary)

  Financial Year  Total_Offences  Records
0        fy22-23           27430     7896
1        fy23-24           44219    12264
2        fy24-25           45880    12595
3        fy25-26           39968    12059
4        fy26-27           14230     4113

In [42]:
financial_year_summary['Percentage_Change'] = (
    financial_year_summary['Total_Offences']
    .pct_change() * 100
)

print(financial_year_summary)

  Financial Year  Total_Offences  Records  Percentage_Change
0        fy22-23           27430     7896                NaN
1        fy23-24           44219    12264          61.206708
2        fy24-25           45880    12595           3.756304
3        fy25-26           39968    12059         -12.885789
4        fy26-27           14230     4113         -64.396517

In [43]:
complete_fy = financial_year_summary[
    financial_year_summary['Financial Year'].isin([
        'fy23-24',
        'fy24-25',
        'fy25-26'
    ])
].copy()

print("Complete financial years:")
print(complete_fy)

Complete financial years:
  Financial Year  Total_Offences  Records  Percentage_Change
1        fy23-24           44219    12264          61.206708
2        fy24-25           45880    12595           3.756304
3        fy25-26           39968    12059         -12.885789

In [44]:
highest_complete_fy = complete_fy.loc[
    complete_fy['Total_Offences'].idxmax()
]

print("\nHighest complete financial year:")
print(highest_complete_fy)

Highest complete financial year:
Financial Year        fy24-25
Total_Offences          45880
Records                 12595
Percentage_Change    3.756304
Name: 2, dtype: object

In [45]:
first_complete = complete_fy.iloc[0]['Total_Offences']
last_complete = complete_fy.iloc[-1]['Total_Offences']

overall_change = (
    (last_complete - first_complete)
    / first_complete
) * 100

print("FY23-24 offences:", first_complete)
print("FY25-26 offences:", last_complete)
print("Overall change:", overall_change, "%")

FY23-24 offences: 44219
FY25-26 offences: 39968
Overall change: -9.613514552567901 %

# Question 3 – Which boroughs have the highest number of knife-crime offences?

In [47]:
#Question 3 :
# Filter only offence records at Borough level
borough_only = clean_df[
    (clean_df['Measure'] == 'Offences') &
    (clean_df['Area Type'] == 'Borough')
].copy()

In [48]:
# Total knife-crime offences by borough
borough_offences = (
    borough_only
    .groupby('Borough_SNT')['Count']
    .sum()
    .reset_index()
    .sort_values('Count', ascending=False)
)

borough_offences.head(10)

      Borough_SNT  Count
24         Newham   4559
21        Lambeth   4533
34    Westminster   4460
28      Southwark   4384
7         Croydon   4364
4           Brent   3646
30  Tower Hamlets   3622
9         Enfield   3588
13       Haringey   3540
11        Hackney   3366

In [49]:
# Top 10 boroughs
top_10_boroughs = borough_offences.head(10)

print(top_10_boroughs)

      Borough_SNT  Count
24         Newham   4559
21        Lambeth   4533
34    Westminster   4460
28      Southwark   4384
7         Croydon   4364
4           Brent   3646
30  Tower Hamlets   3622
9         Enfield   3588
13       Haringey   3540
11        Hackney   3366

In [51]:
highest_borough = borough_offences.iloc[0]

print("Highest-crime borough:")
print(highest_borough)

Highest-crime borough:
Borough_SNT    Newham
Count            4559
Name: 24, dtype: object

# Question 4 – Which Safer Neighbourhood Teams have the highest knife-crime counts?

In [52]:
# Filter only Safer Neighbourhood Team offence records
snt_only = clean_df[
    (clean_df['Measure'] == 'Offences') &
    (clean_df['Area Type'] == 'Safer Neighbourhood Teams')
].copy()

snt_only.head()

,Month_Year,Area Type,Borough_SNT,Area Name,Area Code,Crime Type,Crime Subtype,Measure,Financial Year,Count,Refresh Date
0,2025-02-01,Safer Neighbourhood Teams,Lambeth Brixton Windrush,Brixton Windrush,E05014098,Knife Crime,Knife Crime with Injury,Offences,fy24-25,2,2026-08-18
1,2025-12-01,Safer Neighbourhood Teams,Croydon Selhurst,Selhurst,E05011479,Knife Crime,Knife Crime with Injury,Offences,fy25-26,1,2026-08-18
2,2024-01-01,Safer Neighbourhood Teams,Greenwich Abbey Wood,Abbey Wood,E05014072,Knife Crime,Knife Crime with Injury,Offences,fy23-24,2,2026-08-18
3,2024-12-01,Safer Neighbourhood Teams,Croydon West Thornton,West Thornton,E05011488,Knife Crime,Knife Crime with Injury,Offences,fy24-25,2,2026-08-18
4,2023-02-01,Safer Neighbourhood Teams,Waltham Forest Wood Street,Wood Street,E05013903,Knife Crime,Knife Crime with Injury,Offences,fy22-23,6,2026-08-18

In [53]:
# Total knife-crime offences by Safer Neighbourhood Team
snt_offences = (
    snt_only
    .groupby('Area Name')['Count']
    .sum()
    .reset_index()
    .sort_values('Count', ascending=False)
)

snt_offences.head(15)

                    Area Name  Count
606                   Unknown   2442
643                  West End   1321
546                St James's    913
198       Fairfield (Croydon)    512
197                 Fairfield    452
314                 Hyde Park    431
187            Edmonton Green    428
208             Finsbury Park    417
162                  Deptford    416
66                Broad Green    403
567                 Stratford    392
312  Hoxton East & Shoreditch    391
264  Harlesden & Kensal Green    387
202                   Faraday    364
631     Waterloo & South Bank    361

In [54]:
# Top 10 Safer Neighbourhood Teams
top_10_snt = snt_offences.head(10)

print(top_10_snt)

               Area Name  Count
606              Unknown   2442
643             West End   1321
546           St James's    913
198  Fairfield (Croydon)    512
197            Fairfield    452
314            Hyde Park    431
187       Edmonton Green    428
208        Finsbury Park    417
162             Deptford    416
66           Broad Green    403

In [56]:
highest_snt = snt_offences.iloc[0]

print("Safer Neighbourhood Team with the highest number of offences:")
print(highest_snt)

Safer Neighbourhood Team with the highest number of offences:
Area Name    Unknown
Count           2442
Name: 606, dtype: object

# Question 5 – What is the distribution of knife crime by crime subtype?

In [57]:
# Question 5: Which knife-crime subtype is most common?
# Use offence records only.
subtype_offences = offences_df.copy()

subtype_offences.head()

,Month_Year,Area Type,Borough_SNT,Area Name,Area Code,Crime Type,Crime Subtype,Measure,Financial Year,Count,Refresh Date
0,2025-02-01,Safer Neighbourhood Teams,Lambeth Brixton Windrush,Brixton Windrush,E05014098,Knife Crime,Knife Crime with Injury,Offences,fy24-25,2,2026-08-18
1,2025-12-01,Safer Neighbourhood Teams,Croydon Selhurst,Selhurst,E05011479,Knife Crime,Knife Crime with Injury,Offences,fy25-26,1,2026-08-18
2,2024-01-01,Safer Neighbourhood Teams,Greenwich Abbey Wood,Abbey Wood,E05014072,Knife Crime,Knife Crime with Injury,Offences,fy23-24,2,2026-08-18
3,2024-12-01,Safer Neighbourhood Teams,Croydon West Thornton,West Thornton,E05011488,Knife Crime,Knife Crime with Injury,Offences,fy24-25,2,2026-08-18
4,2023-02-01,Safer Neighbourhood Teams,Waltham Forest Wood Street,Wood Street,E05013903,Knife Crime,Knife Crime with Injury,Offences,fy22-23,6,2026-08-18

In [58]:
# Total offences by Crime Subtype
crime_subtype = (
    subtype_offences
    .groupby('Crime Subtype')['Count']
    .sum()
    .reset_index()
    .sort_values('Count', ascending=False)
)

print(crime_subtype)

                                Crime Subtype   Count
0                                 Knife Crime  117969
1                     Knife Crime with Injury   29228
3                 Knife Injury Victims (1-24)   10845
4          Knife Injury Victims (non DA 1-24)    9915
2  Knife Crime with Injury (Personal Robbery)    3770

In [59]:
# Calculate percentage contribution of each crime subtype
# Display total offences by crime subtype
print("Knife-Crime Offences by Crime Subtype:")
print(crime_subtype[['Crime Subtype', 'Count']])

Knife-Crime Offences by Crime Subtype:
                                Crime Subtype   Count
0                                 Knife Crime  117969
1                     Knife Crime with Injury   29228
3                 Knife Injury Victims (1-24)   10845
4          Knife Injury Victims (non DA 1-24)    9915
2  Knife Crime with Injury (Personal Robbery)    3770

In [61]:
highest_subtype = crime_subtype.iloc[0]

print("Most common knife-crime subtype:")
print(highest_subtype)

Most common knife-crime subtype:
Crime Subtype    Knife Crime
Count                 117969
Name: 0, dtype: object

# Question 6 – How does knife crime with injury compare with overall knife crime?

In [62]:
# Question 6: How does knife crime with injury compare with overall knife crime?
# Use offence records only.
injury_offences = offences_df.copy()

injury_offences.head()

,Month_Year,Area Type,Borough_SNT,Area Name,Area Code,Crime Type,Crime Subtype,Measure,Financial Year,Count,Refresh Date
0,2025-02-01,Safer Neighbourhood Teams,Lambeth Brixton Windrush,Brixton Windrush,E05014098,Knife Crime,Knife Crime with Injury,Offences,fy24-25,2,2026-08-18
1,2025-12-01,Safer Neighbourhood Teams,Croydon Selhurst,Selhurst,E05011479,Knife Crime,Knife Crime with Injury,Offences,fy25-26,1,2026-08-18
2,2024-01-01,Safer Neighbourhood Teams,Greenwich Abbey Wood,Abbey Wood,E05014072,Knife Crime,Knife Crime with Injury,Offences,fy23-24,2,2026-08-18
3,2024-12-01,Safer Neighbourhood Teams,Croydon West Thornton,West Thornton,E05011488,Knife Crime,Knife Crime with Injury,Offences,fy24-25,2,2026-08-18
4,2023-02-01,Safer Neighbourhood Teams,Waltham Forest Wood Street,Wood Street,E05013903,Knife Crime,Knife Crime with Injury,Offences,fy22-23,6,2026-08-18

In [63]:
# Check available crime subtypes
print(injury_offences['Crime Subtype'].unique())

<ArrowStringArray>
[                   'Knife Crime with Injury',
                                'Knife Crime',
                'Knife Injury Victims (1-24)',
         'Knife Injury Victims (non DA 1-24)',
 'Knife Crime with Injury (Personal Robbery)']
Length: 5, dtype: str

In [64]:
# Total offences by crime subtype
injury_count = crime_subtype.loc[
    crime_subtype['Crime Subtype'] == 'Knife Crime with Injury',
    'Count'
].iloc[0]

overall_knife_crime = crime_subtype.loc[
    crime_subtype['Crime Subtype'] == 'Knife Crime',
    'Count'
].iloc[0]

print("Knife Crime:", overall_knife_crime)
print("Knife Crime with Injury:", injury_count)

Knife Crime: 117969
Knife Crime with Injury: 29228

In [65]:
# Compare overall knife crime with knife crime with injury

injury_comparison = pd.DataFrame({
    'Crime Category': [
        'Knife Crime',
        'Knife Crime with Injury'
    ],
    'Count': [
        overall_knife_crime,
        injury_count
    ]
})

# Percentage of the overall Knife Crime count represented by each category.
injury_comparison['Percentage_of_Overall'] = (
    injury_comparison['Count'] / overall_knife_crime
) * 100

# Share within the two-category comparison.
injury_comparison['Share_of_Comparison'] = (
    injury_comparison['Count'] /
    injury_comparison['Count'].sum()
) * 100

print("Knife Crime vs Knife Crime with Injury:")
print(injury_comparison)

print(
    f"Knife Crime with Injury represents "
    f"{(injury_count / overall_knife_crime) * 100:.2f}% "
    f"of the overall Knife Crime count."
)

Knife Crime vs Knife Crime with Injury:
            Crime Category   Count  Percentage_of_Overall  Share_of_Comparison
0              Knife Crime  117969                100.000            80.143617
1  Knife Crime with Injury   29228                 24.776            19.856383
Knife Crime with Injury represents 24.78% of the overall Knife Crime count.

In [67]:
print("Knife Crime:", overall_knife_crime)
print("Knife Crime with Injury:", injury_count)

Knife Crime: 117969
Knife Crime with Injury: 29228

# Question 7 – Which months experience the highest knife-crime offences?

In [68]:
# Question 7: Is there a seasonal pattern in knife crime?
# Filter only offence records.
monthly_offences = offences_df.copy()

monthly_offences.head()

,Month_Year,Area Type,Borough_SNT,Area Name,Area Code,Crime Type,Crime Subtype,Measure,Financial Year,Count,Refresh Date
0,2025-02-01,Safer Neighbourhood Teams,Lambeth Brixton Windrush,Brixton Windrush,E05014098,Knife Crime,Knife Crime with Injury,Offences,fy24-25,2,2026-08-18
1,2025-12-01,Safer Neighbourhood Teams,Croydon Selhurst,Selhurst,E05011479,Knife Crime,Knife Crime with Injury,Offences,fy25-26,1,2026-08-18
2,2024-01-01,Safer Neighbourhood Teams,Greenwich Abbey Wood,Abbey Wood,E05014072,Knife Crime,Knife Crime with Injury,Offences,fy23-24,2,2026-08-18
3,2024-12-01,Safer Neighbourhood Teams,Croydon West Thornton,West Thornton,E05011488,Knife Crime,Knife Crime with Injury,Offences,fy24-25,2,2026-08-18
4,2023-02-01,Safer Neighbourhood Teams,Waltham Forest Wood Street,Wood Street,E05013903,Knife Crime,Knife Crime with Injury,Offences,fy22-23,6,2026-08-18

In [69]:
# Extract month number and month name
monthly_offences['Month'] = monthly_offences['Month_Year'].dt.month
monthly_offences['Month_Name'] = monthly_offences['Month_Year'].dt.month_name()

monthly_offences[['Month_Year', 'Month', 'Month_Name']].head()

  Month_Year  Month Month_Name
0 2025-02-01      2   February
1 2025-12-01     12   December
2 2024-01-01      1    January
3 2024-12-01     12   December
4 2023-02-01      2   February

In [70]:
# Total knife-crime offences by month of year
monthly_pattern = (
    monthly_offences
    .groupby(['Month', 'Month_Name'])['Count']
    .sum()
    .reset_index()
    .sort_values('Month')
)

print(monthly_pattern)

    Month Month_Name  Count
0       1    January  13452
1       2   February  12975
2       3      March  14480
3       4      April  14056
4       5        May  15380
5       6       June  14874
6       7       July  15076
7       8     August  14448
8       9  September  14010
9      10    October  14848
10     11   November  14466
11     12   December  13662

In [71]:
# Rank months by total offences
monthly_ranked = monthly_pattern.sort_values(
    'Count',
    ascending=False
)

print(monthly_ranked)

    Month Month_Name  Count
4       5        May  15380
6       7       July  15076
5       6       June  14874
9      10    October  14848
2       3      March  14480
10     11   November  14466
7       8     August  14448
3       4      April  14056
8       9  September  14010
11     12   December  13662
0       1    January  13452
1       2   February  12975

In [73]:
highest_month = monthly_ranked.iloc[0]
lowest_month = monthly_ranked.iloc[-1]

print("Highest month:")
print(highest_month)

print("\nLowest month:")
print(lowest_month)

Highest month:
Month             5
Month_Name      May
Count         15380
Name: 4, dtype: object

Lowest month:
Month                2
Month_Name    February
Count            12975
Name: 1, dtype: object

# Question 8 – Which areas show the greatest variation in knife crime over time?

In [74]:
# Question 8: Which areas show the greatest variation in knife crime?
# Use offence records only.
area_time = offences_df.copy()

area_time.head()

,Month_Year,Area Type,Borough_SNT,Area Name,Area Code,Crime Type,Crime Subtype,Measure,Financial Year,Count,Refresh Date
0,2025-02-01,Safer Neighbourhood Teams,Lambeth Brixton Windrush,Brixton Windrush,E05014098,Knife Crime,Knife Crime with Injury,Offences,fy24-25,2,2026-08-18
1,2025-12-01,Safer Neighbourhood Teams,Croydon Selhurst,Selhurst,E05011479,Knife Crime,Knife Crime with Injury,Offences,fy25-26,1,2026-08-18
2,2024-01-01,Safer Neighbourhood Teams,Greenwich Abbey Wood,Abbey Wood,E05014072,Knife Crime,Knife Crime with Injury,Offences,fy23-24,2,2026-08-18
3,2024-12-01,Safer Neighbourhood Teams,Croydon West Thornton,West Thornton,E05011488,Knife Crime,Knife Crime with Injury,Offences,fy24-25,2,2026-08-18
4,2023-02-01,Safer Neighbourhood Teams,Waltham Forest Wood Street,Wood Street,E05013903,Knife Crime,Knife Crime with Injury,Offences,fy22-23,6,2026-08-18

In [75]:
# Total offences for each area in each month
area_monthly = (
    area_time
    .groupby(['Borough_SNT', 'Month_Year'])['Count']
    .sum()
    .reset_index()
)

area_monthly.head()

                              Borough_SNT Month_Year  Count
0  Aviation Security (SO18) (Legacy Only) 2023-04-01      1
1  Aviation Security (SO18) (Legacy Only) 2023-05-01      1
2  Aviation Security (SO18) (Legacy Only) 2023-06-01      2
3  Aviation Security (SO18) (Legacy Only) 2023-07-01      2
4  Aviation Security (SO18) (Legacy Only) 2023-09-01      6

In [76]:
# Calculate monthly variation (standard deviation) for each area.
# Use offence records only and exclude non-geographical/unknown areas.

valid_area_monthly = area_monthly[
    ~area_monthly['Borough_SNT'].isin([
        'Unknown',
        'N/K (Legacy Only)',
        'N/K (Legacy Only) N/K'
    ])
].copy()

variation = (
    valid_area_monthly
    .groupby('Borough_SNT')['Count']
    .agg(
        Mean='mean',
        Std_Dev='std',
        Min='min',
        Max='max',
        Months='count'
    )
    .dropna(subset=['Std_Dev'])
    .sort_values('Std_Dev', ascending=False)
)

print("Areas with the greatest monthly variation:")
print(variation.head(10))

Areas with the greatest monthly variation:
                    Mean    Std_Dev  Min  Max  Months
Borough_SNT
Croydon        90.916667  25.092877   50  165      48
Ealing         68.895833  20.674004   28  141      48
Southwark      91.333333  20.562653   50  135      48
Lambeth        94.437500  19.877183   55  147      48
Brent          75.958333  19.678218   35  118      48
Westminster    92.916667  19.502137   55  141      48
Newham         94.979167  18.603923   61  130      48
Haringey       73.750000  17.715842   46  120      48
Tower Hamlets  75.458333  16.314669   39  111      48
Wandsworth     43.729167  15.546416   24   96      48

In [77]:
highest_variation = variation.iloc[0]

print("Area with the greatest variation in knife-crime offences:")
print(highest_variation)

Area with the greatest variation in knife-crime offences:
Mean        90.916667
Std_Dev     25.092877
Min         50.000000
Max        165.000000
Months      48.000000
Name: Croydon, dtype: float64

# Question 9 – What percentage of total knife crime is contributed by the highest-crime areas?

In [79]:
# Question 9: What percentage of total knife crime is contributed by the highest-crime areas?

# Filter only offence records.
area_offences = offences_df.copy()

area_offences.head()

,Month_Year,Area Type,Borough_SNT,Area Name,Area Code,Crime Type,Crime Subtype,Measure,Financial Year,Count,Refresh Date
0,2025-02-01,Safer Neighbourhood Teams,Lambeth Brixton Windrush,Brixton Windrush,E05014098,Knife Crime,Knife Crime with Injury,Offences,fy24-25,2,2026-08-18
1,2025-12-01,Safer Neighbourhood Teams,Croydon Selhurst,Selhurst,E05011479,Knife Crime,Knife Crime with Injury,Offences,fy25-26,1,2026-08-18
2,2024-01-01,Safer Neighbourhood Teams,Greenwich Abbey Wood,Abbey Wood,E05014072,Knife Crime,Knife Crime with Injury,Offences,fy23-24,2,2026-08-18
3,2024-12-01,Safer Neighbourhood Teams,Croydon West Thornton,West Thornton,E05011488,Knife Crime,Knife Crime with Injury,Offences,fy24-25,2,2026-08-18
4,2023-02-01,Safer Neighbourhood Teams,Waltham Forest Wood Street,Wood Street,E05013903,Knife Crime,Knife Crime with Injury,Offences,fy22-23,6,2026-08-18

In [80]:
# Calculate total knife-crime offences for each known area.
valid_area_offences = area_offences[
    ~area_offences['Borough_SNT'].isin([
        'Unknown',
        'N/K (Legacy Only)',
        'N/K (Legacy Only) N/K'
    ])
].copy()

area_totals = (
    valid_area_offences
    .groupby('Borough_SNT')['Count']
    .sum()
    .sort_values(ascending=False)
)

print("Top 10 areas by total knife-crime offences:")
print(area_totals.head(10))

Top 10 areas by total knife-crime offences:
Borough_SNT
Newham           4559
Lambeth          4533
Westminster      4460
Southwark        4384
Croydon          4364
Brent            3646
Tower Hamlets    3622
Enfield          3588
Haringey         3540
Hackney          3366
Name: Count, dtype: int64

In [81]:
# Calculate total knife-crime offences across the known geographical areas.
total_knife_crime = area_totals.sum()

# Top 5 areas
top_5_total = area_totals.head(5).sum()
top_5_percentage = (top_5_total / total_knife_crime) * 100

# Top 10 areas
top_10_total = area_totals.head(10).sum()
top_10_percentage = (top_10_total / total_knife_crime) * 100

print(f"Total knife-crime offences in known areas: {total_knife_crime:,}")
print(f"Top 5 areas: {top_5_total:,} offences ({top_5_percentage:.2f}%)")
print(f"Top 10 areas: {top_10_total:,} offences ({top_10_percentage:.2f}%)")

Total knife-crime offences in known areas: 167,727
Top 5 areas: 22,300 offences (13.30%)
Top 10 areas: 40,062 offences (23.89%)

In [82]:
# Percentage contributed by all areas outside the top 10
other_percentage = 100 - top_10_percentage

print(f"All other known areas: {other_percentage:.2f}%")

All other known areas: 76.11%

In [83]:
# Top 5 and Top 10 areas
top_5 = area_totals.head(5)
top_10 = area_totals.head(10)

# Calculate offence counts
top_5_count = top_5.sum()
top_10_count = top_10.sum()

# Calculate percentage contribution
top_5_percentage = (top_5_count / total_knife_crime) * 100
top_10_percentage = (top_10_count / total_knife_crime) * 100

print(f"Top 5 areas: {top_5_count:,} offences ({top_5_percentage:.2f}%)")
print(f"Top 10 areas: {top_10_count:,} offences ({top_10_percentage:.2f}%)")

Top 5 areas: 22,300 offences (13.30%)
Top 10 areas: 40,062 offences (23.89%)

In [85]:
print("Top 10 highest-crime areas:")
print(top_10)

Top 10 highest-crime areas:
Borough_SNT
Newham           4559
Lambeth          4533
Westminster      4460
Southwark        4384
Croydon          4364
Brent            3646
Tower Hamlets    3622
Enfield          3588
Haringey         3540
Hackney          3366
Name: Count, dtype: int64

# Question 10 – Which areas and periods represent knife-crime hotspots?

In [86]:
#Question 10:
# Filter only offence records
hotspot_data = clean_df[
    clean_df['Measure'] == 'Offences'
].copy()

hotspot_data.head()

,Month_Year,Area Type,Borough_SNT,Area Name,Area Code,Crime Type,Crime Subtype,Measure,Financial Year,Count,Refresh Date
0,2025-02-01,Safer Neighbourhood Teams,Lambeth Brixton Windrush,Brixton Windrush,E05014098,Knife Crime,Knife Crime with Injury,Offences,fy24-25,2,2026-08-18
1,2025-12-01,Safer Neighbourhood Teams,Croydon Selhurst,Selhurst,E05011479,Knife Crime,Knife Crime with Injury,Offences,fy25-26,1,2026-08-18
2,2024-01-01,Safer Neighbourhood Teams,Greenwich Abbey Wood,Abbey Wood,E05014072,Knife Crime,Knife Crime with Injury,Offences,fy23-24,2,2026-08-18
3,2024-12-01,Safer Neighbourhood Teams,Croydon West Thornton,West Thornton,E05011488,Knife Crime,Knife Crime with Injury,Offences,fy24-25,2,2026-08-18
4,2023-02-01,Safer Neighbourhood Teams,Waltham Forest Wood Street,Wood Street,E05013903,Knife Crime,Knife Crime with Injury,Offences,fy22-23,6,2026-08-18

In [87]:
# Total offences for each area in each month
area_month_hotspots = (
    hotspot_data
    .groupby(['Borough_SNT', 'Month_Year'])['Count']
    .sum()
    .reset_index()
)

# Remove unknown/non-geographical areas from hotspot ranking.
area_month_hotspots = area_month_hotspots[
    ~area_month_hotspots['Borough_SNT'].isin([
        'Unknown',
        'N/K (Legacy Only)',
        'N/K (Legacy Only) N/K'
    ])
].sort_values('Count', ascending=False)

print("Top area-month knife-crime hotspots:")
print(area_month_hotspots.head(20))

Top area-month knife-crime hotspots:
       Borough_SNT Month_Year  Count
4387       Croydon 2023-09-01    165
4386       Croydon 2023-08-01    149
14613      Lambeth 2022-10-01    147
23132  Westminster 2022-12-01    141
5390        Ealing 2026-05-01    141
14636      Lambeth 2024-09-01    136
19262    Southwark 2024-02-01    135
19255    Southwark 2023-07-01    134
14638      Lambeth 2024-11-01    132
4389       Croydon 2023-11-01    131
17039       Newham 2025-12-01    130
4393       Croydon 2024-03-01    130
17033       Newham 2025-06-01    130
19270    Southwark 2024-10-01    129
4376       Croydon 2022-10-01    129
17011       Newham 2023-08-01    128
23144  Westminster 2023-12-01    125
17010       Newham 2023-07-01    121
4395       Croydon 2024-05-01    121
17034       Newham 2025-07-01    121

In [88]:
# Top 10 knife-crime hotspots
top_10_hotspots = area_month_hotspots.head(10)

print(top_10_hotspots)

       Borough_SNT Month_Year  Count
4387       Croydon 2023-09-01    165
4386       Croydon 2023-08-01    149
14613      Lambeth 2022-10-01    147
23132  Westminster 2022-12-01    141
5390        Ealing 2026-05-01    141
14636      Lambeth 2024-09-01    136
19262    Southwark 2024-02-01    135
19255    Southwark 2023-07-01    134
14638      Lambeth 2024-11-01    132
4389       Croydon 2023-11-01    131

In [90]:
highest_hotspot = area_month_hotspots.iloc[0]

print("Highest knife-crime hotspot:")
print(highest_hotspot)

Highest knife-crime hotspot:
Borough_SNT                Croydon
Month_Year     2023-09-01 00:00:00
Count                          165
Name: 4387, dtype: object

In [91]:
hotspot_area_frequency = (
    top_10_hotspots['Borough_SNT']
    .value_counts()
    .reset_index()
)

hotspot_area_frequency.columns = ['Borough_SNT', 'Number_of_Top10_Hotspots']

print(hotspot_area_frequency)

   Borough_SNT  Number_of_Top10_Hotspots
0      Croydon                         3
1      Lambeth                         3
2    Southwark                         2
3  Westminster                         1
4       Ealing                         1